In [2]:
import numpy as np

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer(analyzer='word',stop_words=None, lowercase=False)

In [41]:
docs = np.array([
        'X , y = california.data, california.target',
        'X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)',
        'sc.fit(X_train)',
        'X_train_std = sc.fit_transform(X_train)',
        'X_test_std = sc.fit_transform(X_test)'])

In [19]:
docs = np.array([
        'You might be wondering why the updates mechanism exists.', 
        'You can always achieve a similar result by returning the new expressions,', 
        'and working with them in NumPy as usual.',
        'The updates mechanism can be a syntactic convenience,',
        'but it is mainly there for efficiency.',
        'Updates to shared variables can sometimes be done more quickly using in-place algorithms',
        '(e.g. low-rank matrix updates).',
        'Also, Theano has more control over where and how shared variables are allocated,',
        'which is one of the important elements of getting good performance on the GPU.'])

In [55]:
bag = count.build_tokenizer()

In [51]:
bag = count.fit_transform(docs)

In [52]:
print(count.vocabulary_)

{'sc': 9, 'data': 5, 'random_state': 8, 'california': 4, 'y_train': 14, 'test_size': 11, 'fit': 6, 'target': 10, 'y_test': 13, 'X_train_std': 3, 'X_test_std': 1, 'X_train': 2, 'X_test': 0, 'fit_transform': 7, 'train_test_split': 12}


In [53]:
print(count.stop_words_)

set()


In [54]:
print(bag.toarray())

[[0 0 0 0 2 1 0 0 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 1 0 0 1 1 1 1]
 [0 0 1 0 0 0 1 0 0 1 0 0 0 0 0]
 [0 0 1 1 0 0 0 1 0 1 0 0 0 0 0]
 [1 1 0 0 0 0 0 1 0 1 0 0 0 0 0]]
