In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets

In [2]:
#### olivetti faces data
faces = datasets.fetch_olivetti_faces()
X = faces.data
y = faces.target

In [3]:
# data scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)
X = sc.transform(X)

In [233]:
from sklearn.decomposition import PCA
# PCA
n_components = 4096
pca = PCA(n_components=n_components)
pca.fit(X)

PCA(copy=True, n_components=4096, whiten=False)

In [274]:
from sklearn.decomposition import FastICA
n_components = 400
pca = FastICA(n_components = n_components)
pca.fit(X)

FastICA(algorithm='parallel', fun='logcosh', fun_args=None, max_iter=200,
    n_components=400, random_state=None, tol=0.0001, w_init=None,
    whiten=True)

In [190]:
from sklearn.decomposition import SparsePCA
# Sparse PCA
n_components = 40
pca = SparsePCA(n_components=n_components, alpha = 10)
pca.fit(X)

SparsePCA(U_init=None, V_init=None, alpha=10, max_iter=1000, method='lars',
     n_components=40, n_jobs=1, random_state=None, ridge_alpha=0.01,
     tol=1e-08, verbose=False)

In [220]:
from sklearn.decomposition import MiniBatchSparsePCA
# Sparse PCA
n_components = 40
pca = MiniBatchSparsePCA(n_components=n_components, alpha = 5)
pca.fit(X)

MiniBatchSparsePCA(alpha=5, batch_size=3, callback=None, method='lars',
          n_components=40, n_iter=100, n_jobs=1, random_state=None,
          ridge_alpha=0.01, shuffle=True, verbose=False)

In [242]:
# create identity matrix
I = np.identity(n_components)
# obtain coefficients
coef = pca.transform(I)
coef

array([[-10.28389127,   9.50016439, -10.18413655, ...,  -9.79499334,
         10.18851364,   7.47013755],
       [ 10.10387391,  -9.3329509 ,  10.00477379, ...,   9.62468692,
        -10.01122641,  -7.33362143],
       [-16.40399815,  15.15414572, -16.24736495, ..., -15.62429916,
         16.2565911 ,  11.91046095],
       ..., 
       [  6.2800851 ,  -5.80183461,   6.22040783, ...,   5.98094321,
         -6.2227846 ,  -4.55722903],
       [ -8.19481574,   7.57016589,  -8.11612059, ...,  -7.8046483 ,
          8.12062516,   5.95118204],
       [  2.47762474,  -2.2880974 ,   2.45116463, ...,   2.36248307,
         -2.45390732,  -1.79877266]])

In [266]:
i = np.zeros(n_components)
i[0] = 1
X_samples = pca.inverse_transform(i.reshape(1,-1))

In [267]:
# generated face
face = X_samples
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [268]:
# generated face
face = pca.components_[39]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [277]:
# generated face
face = np.zeros(4096)
face = pca.mean_
for i in range(0,399):
    face = face + pca.components_[i]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [276]:
# generated face (mean)
face = pca.mean_
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [213]:
pca.mean_

array([ -3.05026759e-07,   3.86126345e-07,   5.71310522e-07, ...,
        -4.44948682e-07,  -1.13103533e-06,  -5.15952706e-07], dtype=float32)

In [275]:
pca.components_[0]

array([ -9.45295605,   9.28402816, -15.08137493, ...,   5.76803002,
        -7.53484026,   2.27458049])

In [278]:
pca.n_iter_

70

In [19]:
Xmixed = np.zeros(X.shape[1])
for i in range(10):
    Xmixed = Xmixed + X[i]
Xmixed.shape

(4096,)

In [ ]:
col = X.shape[0]

Xmixed = []

In [20]:
from sklearn.decomposition import FastICA
n_components = 40
ica = FastICA(n_components = n_components, algorithm = 'deflation', fun = 'cube')
ica.fit(X)

FastICA(algorithm='deflation', fun='cube', fun_args=None, max_iter=200,
    n_components=40, random_state=None, tol=0.0001, w_init=None,
    whiten=True)

In [12]:
Y = ica.fit_transform(X)
# generated face (Fast ICA)
face = Y[1]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([1, n_components]), cmap=plt.cm.gray)
plt.show()

In [14]:
X[0].shape

(4096,)

In [441]:
ica.mixing_.shape

(4096, 40)

In [459]:
# generated face (Fast ICA)
A = ica.mixing_.T
face = A[1]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [442]:
# generated face (Fast ICA)
face = ica.components_[1]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [403]:
# generated face (Fast ICA)
face = np.zeros(4096)
A = ica.mixing_.T
for i in range(0,n_components):
    face = face + A[i]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [454]:
# generated face (Fast ICA)
Xmix = ica.inverse_transform(Y)
face = Xmix[1]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()

In [458]:
# generated face (Fast ICA)
face = X[1]
plt.subplot(1, 1, 1)
vmax = max(face.max(), -face.min())
plt.imshow(face.reshape([64, 64]), cmap=plt.cm.gray)
plt.show()